server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
#  sql:
#    init:
#      mode: always
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
    driver-class-name: org.postgresql.Driver
#  flyway:
#    enabled: true
#    url: jdbc:postgresql://localhost:5432/polardb_catalog
#    user: user
#    password: password
#    locations: classpath:db/migration
management:
  endpoints:
    web:
      exposure:
        include: refresh